#ifndef PACKED_VARYINGS_UV0_HLSL
#define PACKED_VARYINGS_UV0_HLSL

#ifdef PACKED_VARYINGS_USE_UV0

#ifndef PACKED_VARYINGS_UV0_TYPE
#define PACKED_VARYINGS_UV0_TYPE float2
#endif // PACKED_VARYINGS_UV0_TYPE

#if !defined(PACKED_VARYINGS_INDEX_0)
#define PACKED_VARYINGS_INDEX_0 1
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD0
#elif !defined(PACKED_VARYINGS_INDEX_1)
#define PACKED_VARYINGS_INDEX_1 1
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD1
#elif !defined(PACKED_VARYINGS_INDEX_2)
#define PACKED_VARYINGS_INDEX_2 1
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD2
#elif !defined(PACKED_VARYINGS_INDEX_3)
#define PACKED_VARYINGS_INDEX_3 1
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD3
#elif !defined(PACKED_VARYINGS_INDEX_4)
#define PACKED_VARYINGS_INDEX_4 1
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD4
#elif !defined(PACKED_VARYINGS_INDEX_5)
#define PACKED_VARYINGS_INDEX_5 1
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD5
#elif !defined(PACKED_VARYINGS_INDEX_6)
#define PACKED_VARYINGS_INDEX_6 1
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD6
#elif !defined(PACKED_VARYINGS_INDEX_7)
#define PACKED_VARYINGS_INDEX_7 1
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD7
#elif !defined(PACKED_VARYINGS_INDEX_8)
#define PACKED_VARYINGS_INDEX_8 1
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD8
#elif !defined(PACKED_VARYINGS_INDEX_9)
#define PACKED_VARYINGS_INDEX_9 1
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD9
#elif !defined(PACKED_VARYINGS_INDEX_10)
#define PACKED_VARYINGS_INDEX_10 1
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD10
#elif !defined(PACKED_VARYINGS_INDEX_11)
#define PACKED_VARYINGS_INDEX_11 1
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD11
#elif !defined(PACKED_VARYINGS_INDEX_12)
#define PACKED_VARYINGS_INDEX_12 1
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD12
#elif !defined(PACKED_VARYINGS_INDEX_13)
#define PACKED_VARYINGS_INDEX_13 1
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD13
#elif !defined(PACKED_VARYINGS_INDEX_14)
#define PACKED_VARYINGS_INDEX_14 1
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD14
#elif !defined(PACKED_VARYINGS_INDEX_15)
#define PACKED_VARYINGS_INDEX_15 1
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD15
#else
#error "Too many Packed Varyings"
#endif

PACKED_VARYINGS_UV0_TYPE uv0 : PACKED_VARYINGS_UV0_SYMANTIC;

#endif // PACKED_VARYINGS_USE_UV0
#endif // PACKED_VARYINGS_UV0_HLSL
