#ifndef PACKED_VARYINGS_UV0_HLSL
#define PACKED_VARYINGS_UV0_HLSL

#ifdef PACKED_VARYINGS_USE_UV0

#ifndef PACKED_VARYINGS_UV0_TYPE
#define PACKED_VARYINGS_UV0_TYPE float2
#endif // PACKED_VARYINGS_UV0_TYPE

#if !PACKED_VARYINGS_INDEX_0
#define PACKED_VARYINGS_INDEX_0 true
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD0
#elif !PACKED_VARYINGS_INDEX_1
#define PACKED_VARYINGS_INDEX_1 true
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD1
#elif !PACKED_VARYINGS_INDEX_2
#define PACKED_VARYINGS_INDEX_2 true
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD2
#elif !PACKED_VARYINGS_INDEX_3
#define PACKED_VARYINGS_INDEX_3 true
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD3
#elif !PACKED_VARYINGS_INDEX_4
#define PACKED_VARYINGS_INDEX_4 true
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD4
#elif !PACKED_VARYINGS_INDEX_5
#define PACKED_VARYINGS_INDEX_5 true
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD5
#elif !PACKED_VARYINGS_INDEX_6
#define PACKED_VARYINGS_INDEX_6 true
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD6
#elif !PACKED_VARYINGS_INDEX_7
#define PACKED_VARYINGS_INDEX_7 true
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD7
#elif !PACKED_VARYINGS_INDEX_8
#define PACKED_VARYINGS_INDEX_8 true
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD8
#elif !PACKED_VARYINGS_INDEX_9
#define PACKED_VARYINGS_INDEX_9 true
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD9
#elif !PACKED_VARYINGS_INDEX_10
#define PACKED_VARYINGS_INDEX_10 true
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD10
#elif !PACKED_VARYINGS_INDEX_11
#define PACKED_VARYINGS_INDEX_11 true
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD11
#elif !PACKED_VARYINGS_INDEX_12
#define PACKED_VARYINGS_INDEX_12 true
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD12
#elif !PACKED_VARYINGS_INDEX_13
#define PACKED_VARYINGS_INDEX_13 true
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD13
#elif !PACKED_VARYINGS_INDEX_14
#define PACKED_VARYINGS_INDEX_14 true
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD14
#elif !PACKED_VARYINGS_INDEX_15
#define PACKED_VARYINGS_INDEX_15 true
#define PACKED_VARYINGS_UV0_SYMANTIC TEXCOORD15
#else
#error "Too many Packed Varyings"
#endif

PACKED_VARYINGS_UV0_TYPE uv0 : PACKED_VARYINGS_UV0_SYMANTIC;

#endif // PACKED_VARYINGS_USE_UV0
#endif // PACKED_VARYINGS_UV0_HLSL
